/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Dao.FilmeDao;
import java.util.List;
import javax.swing.JOptionPane;
import model.Filme;

/**
 *
 * @author samue
 */
public class TelaLocarFilmes extends javax.swing.JFrame {

    /**
     * Creates new form TelaLocarFilmes
     */
    public TelaLocarFilmes() {
        initComponents();
        carregarFilmes();
    }

    private void carregarFilmes() {
        try {
            
            JFComboBoxLocacao.removeAllItems();

            FilmeDao filmeDao = new FilmeDao();
            List<Filme> filmes = filmeDao.read();

            for (Filme filme : filmes) {
                JFComboBoxLocacao.addItem(filme.getNomeFilme());
            }

            this.filmesDisponiveis = filmes;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar filmes: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void carregarTabelaFilmes(TelaListaFilmes telaListaFilmes) {
        try {
            
            FilmeDao filmeDao = new FilmeDao();

            List<Filme> filmes = filmeDao.read();

            javax.swing.table.DefaultTableModel modeloTabela = (javax.swing.table.DefaultTableModel) telaListaFilmes.getTabelaFilmes().getModel();

            modeloTabela.setRowCount(0);

            for (Filme filme : filmes) {
                modeloTabela.addRow(new Object[]{
                    filme.getNomeFilme(),
                    filme.getCategoria() != null ? filme.getCategoria().getNome() : "Sem Categoria",
                    filme.getDuracao(),
                    filme.getAnoLancamento(),
                    filme.getQuantidade()
                });
            }

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar filmes: " + e.getMessage());
        }
    }

    private List<Filme> filmesDisponiveis;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JFBotaoSalvarLocacao = new javax.swing.JButton();
        JFBotaoVoltar = new javax.swing.JButton();
        JFComboBoxLocacao = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        JFComboBoxQuantidadeLocacao = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("LOCAÇÃO DE FILMES");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Filmes:");

        JFBotaoSalvarLocacao.setText("Salvar");
        JFBotaoSalvarLocacao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JFBotaoSalvarLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFBotaoSalvarLocacaoActionPerformed(evt);
            }
        });

        JFBotaoVoltar.setText("Voltar");
        JFBotaoVoltar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JFBotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFBotaoVoltarActionPerformed(evt);
            }
        });

        JFComboBoxLocacao.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Quantidade:");

        JFComboBoxQuantidadeLocacao.setBackground(new java.awt.Color(255, 255, 255));
        JFComboBoxQuantidadeLocacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel5)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JFBotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(164, 164, 164)
                                .addComponent(JFBotaoSalvarLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JFComboBoxLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JFComboBoxQuantidadeLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JFComboBoxLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFComboBoxQuantidadeLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JFBotaoSalvarLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFBotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JFBotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFBotaoVoltarActionPerformed
        TelaInicial telaInicial = new TelaInicial();

        telaInicial.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_JFBotaoVoltarActionPerformed

    private void JFBotaoSalvarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFBotaoSalvarLocacaoActionPerformed
        try {
            
            int indiceSelecionado = JFComboBoxLocacao.getSelectedIndex();
            if (indiceSelecionado == -1) {
                JOptionPane.showMessageDialog(this, "Selecione um filme.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Filme filme = filmesDisponiveis.get(indiceSelecionado);

            int quantidadeLocada = Integer.parseInt((String) JFComboBoxQuantidadeLocacao.getSelectedItem());

            if (filme.getQuantidade() < quantidadeLocada) {
                JOptionPane.showMessageDialog(this, "Quantidade locada maior que a disponível no estoque.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int novaQuantidade = filme.getQuantidade() - quantidadeLocada;

            FilmeDao filmeDao = new FilmeDao();
            filmeDao.atualizarQuantidade(filme.getId(), novaQuantidade);

            JOptionPane.showMessageDialog(this, "Filme locado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            carregarFilmes();

            TelaListaFilmes telaListaFilmes = new TelaListaFilmes();
            carregarTabelaFilmes(telaListaFilmes);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao locar filme: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JFBotaoSalvarLocacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new TelaLocarFilmes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JFBotaoSalvarLocacao;
    private javax.swing.JButton JFBotaoVoltar;
    private javax.swing.JComboBox<String> JFComboBoxLocacao;
    private javax.swing.JComboBox<String> JFComboBoxQuantidadeLocacao;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
