/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author samue
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JFBotaoListaFilme = new javax.swing.JButton();
        JFBotaoCadastroFilme = new javax.swing.JButton();
        JFBotaoSobreSistema = new javax.swing.JButton();
        JFBotaoLocar = new javax.swing.JButton();
        JFBotaoDeletarFilmes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("LOCADORA DE FILMES");

        JFBotaoListaFilme.setBackground(new java.awt.Color(204, 204, 204));
        JFBotaoListaFilme.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        JFBotaoListaFilme.setForeground(new java.awt.Color(0, 0, 0));
        JFBotaoListaFilme.setText("Lista de Filmes");
        JFBotaoListaFilme.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JFBotaoListaFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFBotaoListaFilmeActionPerformed(evt);
            }
        });

        JFBotaoCadastroFilme.setBackground(new java.awt.Color(204, 204, 204));
        JFBotaoCadastroFilme.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        JFBotaoCadastroFilme.setForeground(new java.awt.Color(0, 0, 0));
        JFBotaoCadastroFilme.setText("Cadastar Filmes");
        JFBotaoCadastroFilme.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JFBotaoCadastroFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFBotaoCadastroFilmeActionPerformed(evt);
            }
        });

        JFBotaoSobreSistema.setBackground(new java.awt.Color(204, 204, 204));
        JFBotaoSobreSistema.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 8)); // NOI18N
        JFBotaoSobreSistema.setForeground(new java.awt.Color(0, 0, 0));
        JFBotaoSobreSistema.setText("Sobre o Sist.");
        JFBotaoSobreSistema.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JFBotaoSobreSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFBotaoSobreSistemaActionPerformed(evt);
            }
        });

        JFBotaoLocar.setBackground(new java.awt.Color(204, 204, 204));
        JFBotaoLocar.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        JFBotaoLocar.setForeground(new java.awt.Color(0, 0, 0));
        JFBotaoLocar.setText("Locar");
        JFBotaoLocar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JFBotaoLocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFBotaoLocarActionPerformed(evt);
            }
        });

        JFBotaoDeletarFilmes.setBackground(new java.awt.Color(204, 204, 204));
        JFBotaoDeletarFilmes.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        JFBotaoDeletarFilmes.setForeground(new java.awt.Color(0, 0, 0));
        JFBotaoDeletarFilmes.setText("Deletar");
        JFBotaoDeletarFilmes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JFBotaoDeletarFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFBotaoDeletarFilmesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(JFBotaoCadastroFilme)
                .addGap(50, 50, 50)
                .addComponent(JFBotaoListaFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(JFBotaoLocar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(JFBotaoDeletarFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(JFBotaoSobreSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(140, 140, 140)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JFBotaoCadastroFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFBotaoListaFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFBotaoLocar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFBotaoDeletarFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(JFBotaoSobreSistema)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JFBotaoListaFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFBotaoListaFilmeActionPerformed
        TelaListaFilmes telaListaFilmes = new TelaListaFilmes();

        telaListaFilmes.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_JFBotaoListaFilmeActionPerformed

    private void JFBotaoCadastroFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFBotaoCadastroFilmeActionPerformed
        
        TelaCadastroFilmes telaCadastroFilmes = new TelaCadastroFilmes();

        telaCadastroFilmes.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_JFBotaoCadastroFilmeActionPerformed

    private void JFBotaoSobreSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFBotaoSobreSistemaActionPerformed
        TelaSobreOSistema telaSobreOSistema = new TelaSobreOSistema();

        telaSobreOSistema.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_JFBotaoSobreSistemaActionPerformed

    private void JFBotaoLocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFBotaoLocarActionPerformed
        
        TelaLocarFilmes telaLocarFilmes = new TelaLocarFilmes();

        telaLocarFilmes.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_JFBotaoLocarActionPerformed

    private void JFBotaoDeletarFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFBotaoDeletarFilmesActionPerformed
        TelaDeletarFilmes telaDeletarFilmes = new TelaDeletarFilmes();

        telaDeletarFilmes.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_JFBotaoDeletarFilmesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JFBotaoCadastroFilme;
    private javax.swing.JButton JFBotaoDeletarFilmes;
    private javax.swing.JButton JFBotaoListaFilme;
    private javax.swing.JButton JFBotaoLocar;
    private javax.swing.JButton JFBotaoSobreSistema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
