/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Dao.CategoriaDao;
import Dao.FilmeDao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import factory.ConnectionFactory;
import model.Categoria;
import model.Filme;
import java.sql.SQLException;

/**
 *
 * @author samue
 */
public class TelaCadastroFilmes extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroFilmes
     */
    public TelaCadastroFilmes() {
        initComponents();
        carregarCategorias();
        configurarBotaoSalvar();
    }

    private void abrirTelaCadastroCategoria() {
        TelaCadastroCategoria telaCadastroCategoria = new TelaCadastroCategoria(this);
        telaCadastroCategoria.setVisible(true);
        this.setVisible(false);
    }

    public void carregarCategorias() {
        try (Connection connection = ConnectionFactory.createConnection()) {
            String sql = "SELECT nome FROM categorias";
            PreparedStatement stmt = connection.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();

            ArrayList<String> categorias = new ArrayList<>();
            while (rs.next()) {
                categorias.add(rs.getString("nome"));
            }
            JFCateforiaFilme.setModel(new DefaultComboBoxModel<>(categorias.toArray(new String[0])));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar categorias: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void configurarBotaoSalvar() {
        JFBotaoSalvarCadastroFilme.addActionListener(evt -> {
            try {
                String nome = JFNomeFilme.getText();
                String duracao = JFDuracaoFilme.getSelectedItem().toString();
                int anoLancamento = Integer.parseInt(JFLancamentoFilme.getText());

                if (JFQuantidadeFilme.getText().isEmpty()) {
                    throw new IllegalArgumentException("O campo de quantidade total não pode estar vazio.");
                }
                int quantidade = Integer.parseInt(JFQuantidadeFilme.getText());

                String nomeCategoria = JFCateforiaFilme.getSelectedItem().toString();

                try (Connection connection = ConnectionFactory.createConnection()) {
                    CategoriaDao categoriaDao = new CategoriaDao(connection);
                    int categoriaId = categoriaDao.getIdByNome(nomeCategoria);

                    Categoria categoria = new Categoria();
                    categoria.setId(categoriaId);
                    categoria.setNome(nomeCategoria);

                    Filme filme = new Filme(nome, anoLancamento, duracao, categoria, quantidade);

                    FilmeDao filmeDao = new FilmeDao(connection);
                    filmeDao.create(filme);

                    JOptionPane.showMessageDialog(null, "Filme salvo com sucesso!");
                    limparCampos();
                } catch (SQLException e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Erro ao salvar filme: " + e.getMessage());
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Erro ao converter valores: " + e.getMessage());
            } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro inesperado: " + e.getMessage());
            }
        });
    }

    private void limparCampos() {
        JFNomeFilme.setText("");
        JFDuracaoFilme.setSelectedIndex(0);
        JFLancamentoFilme.setText("");
        JFQuantidadeFilme.setText("");
        JFCateforiaFilme.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JFNomeFilme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JFDuracaoFilme = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JFLancamentoFilme = new javax.swing.JTextField();
        JFCateforiaFilme = new javax.swing.JComboBox<>();
        JFBotaoAdicionarCategoria = new javax.swing.JButton();
        JFBotaoSalvarCadastroFilme = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        JFQuantidadeFilme = new javax.swing.JTextField();
        JFBotaoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CADASTRO DE FILMES");

        JFNomeFilme.setBackground(new java.awt.Color(204, 204, 204));
        JFNomeFilme.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome do Filme:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Duração:");

        JFDuracaoFilme.setBackground(new java.awt.Color(204, 204, 204));
        JFDuracaoFilme.setForeground(new java.awt.Color(0, 0, 0));
        JFDuracaoFilme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1h", "1h15min", "1h30min", "1h45min", "2h", "2h15min", "2h30min", "2h45min", "3h", "3h15min" }));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ano de Lançamento:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Categoria: ");

        JFLancamentoFilme.setBackground(new java.awt.Color(204, 204, 204));
        JFLancamentoFilme.setForeground(new java.awt.Color(0, 0, 0));

        JFCateforiaFilme.setBackground(new java.awt.Color(255, 255, 255));
        JFCateforiaFilme.setForeground(new java.awt.Color(0, 0, 0));
        JFCateforiaFilme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ação", "Drama", "Comédia" }));

        JFBotaoAdicionarCategoria.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        JFBotaoAdicionarCategoria.setText("Adicionar");
        JFBotaoAdicionarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFBotaoAdicionarCategoriaActionPerformed(evt);
            }
        });

        JFBotaoSalvarCadastroFilme.setText("Salvar");
        JFBotaoSalvarCadastroFilme.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JFBotaoSalvarCadastroFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFBotaoSalvarCadastroFilmeActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Quantidade Disponível:");

        JFQuantidadeFilme.setBackground(new java.awt.Color(204, 204, 204));
        JFQuantidadeFilme.setForeground(new java.awt.Color(0, 0, 0));

        JFBotaoVoltar.setText("Voltar");
        JFBotaoVoltar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JFBotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFBotaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JFNomeFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JFQuantidadeFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JFBotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(370, 370, 370)
                        .addComponent(JFBotaoSalvarCadastroFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JFLancamentoFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(JFDuracaoFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JFCateforiaFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JFBotaoAdicionarCategoria)))
                .addGap(118, 118, 118))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JFNomeFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JFDuracaoFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JFLancamentoFilme))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JFQuantidadeFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFCateforiaFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFBotaoAdicionarCategoria))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JFBotaoSalvarCadastroFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFBotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JFBotaoAdicionarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFBotaoAdicionarCategoriaActionPerformed
        
        abrirTelaCadastroCategoria();
    }//GEN-LAST:event_JFBotaoAdicionarCategoriaActionPerformed

    private void JFBotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFBotaoVoltarActionPerformed
        
        TelaInicial telaInicial = new TelaInicial();

        telaInicial.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_JFBotaoVoltarActionPerformed

    private void JFBotaoSalvarCadastroFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFBotaoSalvarCadastroFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JFBotaoSalvarCadastroFilmeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroFilmes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JFBotaoAdicionarCategoria;
    private javax.swing.JButton JFBotaoSalvarCadastroFilme;
    private javax.swing.JButton JFBotaoVoltar;
    private javax.swing.JComboBox<String> JFCateforiaFilme;
    private javax.swing.JComboBox<String> JFDuracaoFilme;
    private javax.swing.JTextField JFLancamentoFilme;
    private javax.swing.JTextField JFNomeFilme;
    private javax.swing.JTextField JFQuantidadeFilme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
